### ISSUE TITLE
Cannot import istype: istype.internal is not packaged on pypi

### ISSUE THREAD

**Issue by thilp** [Cologler/istype-python#1]
Hello, thank you for sharing your work. Unfortunately the current version packaged on pypi cannot be used because it is missing the `internal` directory. Installing from the repository directly works fine.

Steps to reproduce:
```bash
$ mkdir testing-istype && cd testing-istype && pwd
/tmp/testing-istype
$ python3 -m venv istype-venv
$ source istype-venv/bin/activate
(istype-venv) $ pip install istype
Collecting istype
  Using cached https://files.pythonhosted.org/packages/6a/d5/57255f3d4c3e6c002658f7a7e6f59d27b0d24167f30905ce4d1a1971f4f9/istype-0.1.2.0.tar.gz
Installing collected packages: istype
  Running setup.py install for istype ... done
Successfully installed istype-0.1.2.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(istype-venv) $ python
Python 3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from istype import issubclassof
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/testing-istype/istype-venv/lib64/python3.6/site-packages/istype/__init__.py", line 9, in <module>
    from .internal.common import isinstanceof, issubclassof
ModuleNotFoundError: No module named 'istype.internal'
>>> import istype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/testing-istype/istype-venv/lib64/python3.6/site-packages/istype/__init__.py", line 9, in <module>
    from .internal.common import isinstanceof, issubclassof
ModuleNotFoundError: No module named 'istype.internal'
```

Inspecting the installation directory reveals that the whole `internal` directory is missing:
```bash
$ cd /tmp/testing-istype/istype-venv/lib64/python3.6/site-packages/istype/                             
$ ls
__init__.py  __pycache__
```

**Comment by Cologler** [comment]
Updated to v0.1.2.1.

**Important: This is a unstable package (version < 1) with very few unittests.**
